name: Mirror to Vercel Repo
run-name: ${{ github.actor }} mirrors main branch to Vercel 🚀

# Workflow permissions
permissions:
  contents: read # Needed to read repository content
  packages: write # Needed if writing packages (optional for your workflow)
  actions: write
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - main # Trigger on pushes to main
  workflow_dispatch: # Allow manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Mirror to personal Vercel repo
      - name: Mirror to Vercel repo
        run: |
          echo "Setting up git config..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Removing existing vercel remote if exists..."
          git remote remove vercel || true

          echo "Adding vercel remote..."
          git remote add vercel https://owais-aitf:${{ secrets.VERCEL_PAT }}@github.com/owais-aitf/vercel-frontend-deploy.git


          echo "Verifying remote was added..."
          git remote -v

          echo "Pushing to vercel repository..."
          git push vercel main --force
