name: Mirror to Vercel Repo
run-name: ${{ github.actor }} mirrors main branch to Vercel 🚀

permissions:
  contents: read # Needed to read repo content
  packages: write # Needed if writing packages
  actions: write
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - main # Trigger on pushes to main
  workflow_dispatch: # Allow manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source repo using PAT
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VERCEL_PAT }}

      # 2️⃣ Setup Git and add Vercel remote using PAT
      - name: Setup Git authentication
        run: |
          echo "Setting up git config..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "Removing existing vercel remote if exists..."
          git remote remove vercel 2>$null || true

          echo "Adding vercel remote with PAT..."
          git remote add vercel https://owais-aitf:${{ secrets.VERCEL_PAT }}@github.com/owais-aitf/vercel-frontend-deploy.git

          echo "Verifying remote..."
          git remote -v

          echo "Checking if we can access the remote..."
          git ls-remote vercel

      # 3️⃣ Push to Vercel repo
      - name: Push to Vercel repo
        run: |
          echo "Pushing main branch to vercel..."
          git push vercel main --force
